//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iserv.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int MessageID { get; set; }
        public Nullable<System.DateTime> DateSent { get; set; }
        public Nullable<System.TimeSpan> TimeSent { get; set; }
        public string MessageBody { get; set; }
        public string SentFrom { get; set; }
        public string MesseageLocation { get; set; }
        public string MessageSentTo { get; set; }
    }
}
