//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iserv.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceProvider_ServiceRequest
    {
        public int SP_SR_ID { get; set; }
        public Nullable<int> ServiceProvider_ID { get; set; }
        public Nullable<int> ServiceRequestID { get; set; }
        public Nullable<int> ServiceQuoteID { get; set; }
    
        public virtual ServiceProvider ServiceProvider { get; set; }
        public virtual ServiceQuote ServiceQuote { get; set; }
    }
}
