//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iserv.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceQuoteLine
    {
        public int ServiceQuoteLine_ID { get; set; }
        public Nullable<int> ServiceQuoteID { get; set; }
        public string ItemDescription { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> ItemPrice { get; set; }
        public Nullable<decimal> ItemTotal { get; set; }
    
        public virtual ServiceQuote ServiceQuote { get; set; }
    }
}
