//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iserv.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service_Provider_Application
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Service_Provider_Application()
        {
            this.ScheduleAppoitnments = new HashSet<ScheduleAppoitnment>();
        }
    
        public int SPA_ID { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string ldimage { get; set; }
        public Nullable<int> SPA_Status_ID { get; set; }
        public Nullable<int> ServiceID { get; set; }
        public string Surname { get; set; }
        public string IdNumber { get; set; }
        public Nullable<int> GenderID { get; set; }
        public string BusinessName { get; set; }
        public string VatNumber { get; set; }
        public string StreetName { get; set; }
        public string StreetNumber { get; set; }
        public Nullable<int> ProvinceID { get; set; }
        public Nullable<int> CityID { get; set; }
        public string Password { get; set; }
        public string CellNumber { get; set; }
    
        public virtual City City { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual Province Province { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScheduleAppoitnment> ScheduleAppoitnments { get; set; }
        public virtual Service_Provider_Application_Status Service_Provider_Application_Status { get; set; }
    }
}
