//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iserv.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ServiceOrder()
        {
            this.ServiceOrder_Rating = new HashSet<ServiceOrder_Rating>();
            this.ServiceOrderLines = new HashSet<ServiceOrderLine>();
        }
    
        public int ServiceOrderID { get; set; }
        public Nullable<int> Service_Order_Status_ID { get; set; }
        public Nullable<int> ServiceQuoteID { get; set; }
        public Nullable<int> ServiceProvider_ID { get; set; }
        public Nullable<int> ConsumerID { get; set; }
        public Nullable<System.DateTime> datecompleted { get; set; }
    
        public virtual Consumer Consumer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceOrder_Rating> ServiceOrder_Rating { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceOrderLine> ServiceOrderLines { get; set; }
        public virtual ServiceOrder_Status ServiceOrder_Status { get; set; }
        public virtual ServiceQuote ServiceQuote { get; set; }
        public virtual ServiceProvider ServiceProvider { get; set; }
    }
}
