//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iserv.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceQuote
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ServiceQuote()
        {
            this.ServiceOrders = new HashSet<ServiceOrder>();
            this.ServiceOrderLines = new HashSet<ServiceOrderLine>();
            this.ServiceProvider_ServiceRequest = new HashSet<ServiceProvider_ServiceRequest>();
            this.ServiceQuoteLines = new HashSet<ServiceQuoteLine>();
            this.Invoices = new HashSet<Invoice>();
        }
    
        public int ServiceQuoteID { get; set; }
        public Nullable<double> Total { get; set; }
        public Nullable<int> PaymentMethod_ID { get; set; }
        public Nullable<int> ServiceQuote_Status_ID { get; set; }
        public Nullable<int> ConsumerID { get; set; }
        public Nullable<int> ServiceProvider_ID { get; set; }
        public Nullable<int> ServiceRequestID { get; set; }
        public Nullable<System.DateTime> ValidUntil { get; set; }
    
        public virtual Consumer Consumer { get; set; }
        public virtual PaymentMethod PaymentMethod { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceOrder> ServiceOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceOrderLine> ServiceOrderLines { get; set; }
        public virtual ServiceProvider ServiceProvider { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceProvider_ServiceRequest> ServiceProvider_ServiceRequest { get; set; }
        public virtual ServiceQuoteStatu ServiceQuoteStatu { get; set; }
        public virtual ServiceRequest ServiceRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceQuoteLine> ServiceQuoteLines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice> Invoices { get; set; }
    }
}
