//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iserv.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ServiceRequest()
        {
            this.Invoices = new HashSet<Invoice>();
            this.ServiceQuotes = new HashSet<ServiceQuote>();
            this.ServiceRequestLines = new HashSet<ServiceRequestLine>();
        }
    
        public int ServiceRequestID { get; set; }
        public string Service_Description { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Address_ID { get; set; }
        public Nullable<int> ConsumerID { get; set; }
        public Nullable<int> ServiceID { get; set; }
        public string ImagePath { get; set; }
        public Nullable<System.DateTime> datecreated { get; set; }
        public Nullable<int> TimeID { get; set; }
        public Nullable<int> ServiceRequest_Status_ID { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Consumer Consumer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice> Invoices { get; set; }
        public virtual Service Service { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceQuote> ServiceQuotes { get; set; }
        public virtual Time Time { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceRequestLine> ServiceRequestLines { get; set; }
    }
}
