//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iserv.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceOrderLine
    {
        public int ServiceOrderLineID { get; set; }
        public Nullable<int> SericeOrderID { get; set; }
        public Nullable<int> Service_ID { get; set; }
        public Nullable<int> ServiceQuote_ID { get; set; }
        public Nullable<int> ServiceQuoteLine_ID { get; set; }
    
        public virtual Service Service { get; set; }
        public virtual Service Service1 { get; set; }
        public virtual ServiceOrder ServiceOrder { get; set; }
        public virtual ServiceQuote ServiceQuote { get; set; }
    }
}
